# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fe30dfa4c4fe2b25719b671dfaa7c7ec0e32f485c6bfdf051f16c7de492c11aa65326815a78ec1aeea55c05593dc4c77cc5b23b11d329a74e6fbdaabd4f9f8

test:
  secret_key_base: a8d197ab48053ecd2b4d6a26239045b7d5964cae9bee4bfba20bd4b758c9476bfc844f65fe77a4900cfe840afe61a5d3be62319f7fd3203b9178d74778823ea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
